### ISSUE TITLE
Three updates to AI purpose

### ISSUE THREAD

**Issue by Sput** [enricoros/nextjs-chatgpt-app#8] opened 2023-03-20 01:34 UTC
Really enjoying playing with this, I think you have the beginnings of a really useful product.

1. For my purposes, I would prefer to have the AI purpose dropdown to be visible along with the chat window. 
2. I would like to be able to change the AI purpose without refreshing the page. If the item above was implemented, then you could change the AI purpose without refreshing the page.
3. The API allows for more context to be submitted with the prompt. Currently you support the 'system' role, but the API also supports 'user' and 'assistant' roles in this style:
{"role": "system", "content": "You are the assistant to a Dungeon Master running the game 'Dungeons and Dragons'."},        
{"role": "user", "content": "How much damage does magic missile do when cast from a 5th level spell slot?"},           
{"role": "assistant", "content": "When cast at 5th level, magic missile deals 5d4 + 5 force damage,"},

**Comment by enricoros** [comment] 2023-03-20 19:47
What if on the top bar (it says 'gpt-4' now) we have a selectable network and purpose. So it could say "3.5-Turbo - Developer", or "GPT-4 - Scientist".

Hovering the 2 parts will show a dropdown box to change the network or change the purpose, which will apply to the very next reply. Technically, despite having the system message being the initial message of a conversation, I believe it wouldn't be a problem to replace the system message on the fly - i.e. hopefully a former 'purpose' will not anchor the conversation too deeply to that former purpose.

Another possibility is to have 'purpose' as different actors in the conversation. For instance "Developer has entered the chat" while you're having a conversation with the Dungeon Master.

Which implementations would work better, a single chat with switchable purpose, or more actors dropped into the chat?

**Comment by Sput** [comment] 2023-03-20 20:01
Also to address your design idea of the selectable network and purpose, yes, that's exactly how I envisioned it, you understood my idea exactly.

**Comment by enricoros** [comment] 2023-03-22 08:24
Getting there. Now the state is synchronized across the application, and reflected on the top bar.
We're almost at the stage of selecting the nets/roles from the top bar.

![image](https://user-images.githubusercontent.com/32999/226842391-83219988-e488-40ef-95c2-74944e7ffb49.png)

**Comment by enricoros** [comment] 2023-03-24 07:45
I'm thinking of adding an editor for 'purposes', so that you'd be able to have multiple custom purposes, tailor them to your needs, and switch quickly between them. Lmk if an editor (not a small feature) will work.

**Comment by Sput** [comment] 2023-03-31 11:39
I apologize for the late response. I think your recommendation makes sense, right now I'm editing them in the code, which works for developers, but won't scale to normal users.

**Comment by enricoros** [comment] 2023-04-05 03:58
Hi @Sput, the project has made large progress lately. Have you updated your workflow, and do you have a good system prompt to share? I'm thinking at how to offer good editing (#35 ) or customization either with UI, or simply maintaining a json file.
Would love to hear your inputs.

**Comment by enricoros** [comment] 2023-04-05 04:01
> * For my purposes, I would prefer to have the AI purpose dropdown to be visible along with the chat window.

**1. This is done!**

> 2\. I would like to be able to change the AI purpose without refreshing the page. If the item above was implemented, then you could change the AI purpose without refreshing the page.

**2. This is done!**

> 3\. The API allows for more context to be submitted with the prompt. Currently you support the 'system' role, but the API also supports 'user' and 'assistant' roles in this style:

3. I think this is duplicate of #35 . Will close this for now, and will reopen when I hear information about what's the different ask in this (see my former message)

**Closed by enricoros** 2023-04-05 04:01 UTC
Labels: question

**Comment by Sput** [comment] 2023-04-06 19:40
thank you for this, your updates are great, coming fast and furious! I think prompt sharing is the next great frontier. I haven't found any sites that I think do this well. To do that right, its probably a whole other app that would need to be built (maybe I'll be the one to build it). Until then, I'm going to start a discussion thread, and supply mine, see if others have content to add.

**Comment by enricoros** [comment] 2023-04-07 12:46
> coming fast and furious
Thanks :) Tonight we have pixel perfection (markdown and some tiles update) - wait for something really cool really soon.

> maybe I'll be the one to build it
Would love so! and you should have some central API/repository that I can query from this app as well

> I'm going to start a discussion thread, and supply mine, see if others have content to add.
Please do!!
