### ISSUE TITLE
Tabualar or tables

### ISSUE THREAD

**Issue by rossman22590** [enricoros/nextjs-chatgpt-app#39] opened 2023-03-31 04:27 UTC
when the bot makes tables, it doesn't make nice tables looking in css it does it in code like structure using lines and raw text unformatted

**Comment by rossman22590** [comment] 2023-03-31 04:27
try asking for a table of good jobs  to reproduce

**Comment by enricoros** [comment] 2023-03-31 10:52
Duplicate of #11

**Closed by enricoros** 2023-03-31 10:52 UTC
